services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: p-risk-manager
    image: p-risk-manager:1.0.0
    ports:
      - "1305:1305"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
